[package]
name = "scottricity/placementservice"
version = "0.1.2"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
description = "Clone of https://github.com/zblox164/PlacementService"
[dependencies]
